const CommonString = {

    //HeaderTxt 

 Home : "Home",
 StoreListTitle : 'Select a store and get started',
 CheckIn : 'Checked-in',
 EnterStore : 'Enter store',
 ExitStore : 'Exit store',
 EnterStoreAlert : 'Please enter the store to take pictures. You can still browse your previous images',
 EnterStoreAlready: 'You’re already inside another store Exit now to enter a new store',
 StoreDetailsTitle :  'Enter store and select a fixture to proceed',
 ViewResult: 'View Results',
 Save : 'Save',
 GuideLinesPhotoTitle : 'Please read these camera guidelines for a better image recognition',
 GuideLinesVideoTitle : 'Please read these camera guidelines for a better video recognition',
 GuideLinesPhotoTxt1: 'Start taking pictures from left to right',
 GuideLinesPhotoTxt2: 'Make sure the product face is clearly visible (remove if there are any obstacles)',
GuideLinesPhotoTxt3 : 'Kindly hold the phone 3-4 feet away from the rack/shelf, for a full segement image',
GuideLinesVideoTxt1: 'Start taking video from left to right',
GuideLinesVideoTxt2: 'You can take only one single video to cover all the planogram segments Make sure the product face is clearly visible (remove if there are any obstacles)',
GuideLinesVideoTxt3 : 'Kindly hold the phone 3-4 feet away from the rack/shelf, for a full segement image',
DontAskTxt : "Don't ask me again",
ImageCaptured : 'Image Captured',
ImageSaved : 'Image Saved',
GotIt : 'Got it',
Done : "Done",
Retake : "Retake",
Summary : "Summary",
Missing : "Missing",
Misplaced : "Misplaced",
Images : "Images",
PlanogramKpis : "Planogram KPI’s",
ShelfKpis : "Shelf KPI’s",
Analyse : "Analyse",
Analyze : "analysis",
Analyzing : "Analyzing..",
AnalyzedSuccess : "Analyzed successfully",
ViewReport : "View report",
LocationAlert: "Turn on Location Services to allow to determine your location.",
GoToSettings : "Open Settings",
GalleryAccess : "Gallery Access required",
GallerySettingAlert : "Tap the Open Settings button below to open the settings app",
Yes : "Yes",
No : "No",
INPROGRESS : "In-Progress",
NOOFFACINGS : "No of facings:",
UPC : "UPC:",
MISSING : "missing",
MISPLACED : "misplaced",
};

export default CommonString;